[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RootReadme"
version = "0.1"

[project.entry-points."mkdocs.plugins"]
RootReadme = "RootReadme.plugin:RootReadme"
