name: Check broken links
on:
  schedule:
    - cron: '0 8 * * *'
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  LinkChecker:
    name: Link Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      actions: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Get latest curl version from GitHub API
        id: curl_version
        run: |
          version=$(curl -s https://api.github.com/repos/curl/curl/releases/latest | jq -r '.tag_name' | sed 's/curl-//' | sed 's/_/./g')
          echo "latest_version=$version" >> $GITHUB_OUTPUT

      - name: Lychee Broken Link Checker
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          # Check all markdown files in repo but exclude language folders under docs
          args: >-
            --root-dir "${{ github.workspace }}/docs"
            --user-agent "curl/${{ steps.curl_version.outputs.latest_version }}"
            --no-progress
            --max-redirects 100
            --accept 200,403,429,500
            './**/*.md'
            --exclude './ar/**'
            --exclude './de/**'
            --exclude './en/**'
            --exclude './es/**'
            --exclude './fr/**'
            --exclude './hu/**'
            --exclude './id/**'
            --exclude './it/**'
            --exclude './ja/**'
            --exclude './ko/**'
            --exclude './nl/**'
            --exclude './pl/**'
            --exclude './pt/**'
            --exclude './pt-BR/**'
            --exclude './ru/**'
            --exclude './sv/**'
            --exclude './tr/**'
            --exclude './uk/**'
            --exclude './vi/**'
            --exclude './zh-CN/**'
            --exclude './zh-TW/**'
          fail: true
          output: lychee-report.md

      - name: Upload Lychee report artifact
        if: failure()
        uses: actions/upload-artifact@v5.0.0
        with:
          name: lychee-report
          path: lychee-report.md
          retention-days: 30

      # To avoid automated spam, try to find an existing open issue before opening a new one
      # Source: https://github.com/cilium/tetragon/pull/805
      - name: Search for existing issue number
        id: search-issue
        if: always()
        run: |
          encoded_issue_name=$(echo "$ISSUE_NAME" | sed 's/ /%20/g')
          response=$(curl -s -X GET "https://api.github.com/search/issues?q=$encoded_issue_name+repo:sandboxie-plus/sandboxie-docs+state:open+label:automated-report&type=Issues")
          issue_number=$(echo "$response" | jq -r '.items[0].number // empty')
          echo "issue_number=$issue_number" >> $GITHUB_OUTPUT

      - name: Create issue from file
        if: always() && env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: ${{ steps.search-issue.outputs.issue_number }}
          labels: automated-report
